let productos = {
    listaDeProductos: [
        {
            id:0,
            id_usuario:0,
            pieza: "Collar Mon Coeur Oro",
            material: "Oro amarillo",
            precio: 16.900,
            descripcion: "Oro de 24 quilates: también conocido como oro puro, es el tipo de oro más puro que se puede encontrar en el mercado. Contiene un 99,9% de oro.",
            imagen: "/images/products/collarCorazon.jpeg",
            fecha_modificacion: null,
            fecha_borrar: null,
            fecha_creado: null,
        },
        {
            id:1,
            id_usuario:1,
            pieza: "Aros FIORE",
            material: "Oro amarillo",
            precio: 14.000,
            descripcion: "Oro de 10 quilates: contiene un 41,7% de oro y un 58,3% de otros metales.",
            imagen: "/images/products/arosLargos.jpeg",
            fecha_modificacion: null,
            fecha_borrar: null,
            fecha_creado: null,
        },
        {
            id:2,
            id_usuario:2,
            pieza: "Collar inicial enchapado en oro",
            material: "Oro amarillo",
            precio: 15.000,
            descripcion: "Oro de 14 quilates: contiene un 58,3% de oro y un 41,7% de otros metales.",
            imagen: "/images/products/inicialA.jpeg",
            fecha_modificacion: null,
            fecha_borrar: null,
            fecha_creado: null,
        },
        {
            id:3,
            id_usuario:3,
            pieza: "Anillo Abbondanza",
            material: "Bronce",
            precio: 13.000,
            descripcion: "Creamos este anillo de bronce que contiene la piedra Pirita conocida como la piedra de la abundancia.",
            imagen: "/images/products/anilloPierdas.jpeg",
            fecha_modificacion: null,
            fecha_borrar: null,
            fecha_creado: null,
        },
        {
            id:4,
            id_usuario:4,
            pieza: "Collar Chloe personalizado",
            material: "Oro amarillo",
            precio: 12.000,
            descripcion: "Enchapado en Oro Amarillo",
            imagen: "/images/products/collarValen.jpeg",
            fecha_modificacion: null,
            fecha_borrar: null,
            fecha_creado: null,
        },
        {
            id:5,
            id_usuario:5,
            pieza: "Pulsera Cleopatra",
            material: "Oro amarillo con piedras azuladas",
            precio: 14.000,
            descripcion: "Enchapado en Oro Amarillo",
            imagen: "/images/products/pulseraPierdas.jpeg",
            fecha_modificacion: null,
            fecha_borrar: null,
            fecha_creado: null,
        },
        {
            id:6,
            id_usuario:6,
            pieza: "Aros Ivanja",
            material: "Oro amarillo",
            precio: 13.500,
            descripcion: "Baniados en Oro Amarillo",
            imagen: "/images/products/argollasIvanka.jpeg",
            fecha_modificacion: null,
            fecha_borrar: null,
            fecha_creado: null,
        },
        {
            id:7,
            id_usuario:7,
            pieza: "Brazalete Cobalto",
            material: "Oro amarillo y piedras de color Cobalto",
            precio: 17.000,
            descripcion: "Oro de 14 quilates: contiene un 58,3% de oro y un 41,7% de otros metales.",
            imagen: "/images/products/fotoAzul.jpeg",
            fecha_modificacion: null,
            fecha_borrar: null,
            fecha_creado: null,
        },
        {
            id:8,
            id_usuario:8,
            pieza: "Anillo y pulsera Mercury",
            material: "Oro amarillo",
            precio: 14.000,
            descripcion: "Oro de 18 quilates: contiene un 75% de oro y un 25% de otros metales como el cobre, la plata y el paladio.",
            imagen: "/images/products/pulseraYanillos.jpeg",
            fecha_modificacion: null,
            fecha_borrar: null,
            fecha_creado: null,
        },
        {
            id:9,
            id_usuario:9,
            pieza: "Collar Mali Baniado en Oro",
            material: "Oro amarillo",
            precio: 16.000,
            descripcion: "Oro de 24 quilates: también conocido como oro puro, es el tipo de oro más puro que se puede encontrar en el mercado. Contiene un 99,9% de oro.",
            imagen: "/images/products/blazerBlanco.jpeg",
            fecha_modificacion: null,
            fecha_borrar: null,
            fecha_creado: null,
        },


    ],

    usuario: [
        {
            id: 0,
            username: `Guillermina Lopez`,
            email: `Glopez@gmail.com`,
            contrasena: `documento`,
            fecha_nacimiento: `1998-03-18`,
            dni: "44917243",
            image: "https://cdn.icon-icons.com/icons2/2859/PNG/512/avatar_face_girl_female_woman_profile_smiley_happy_people_icon_181665.png",
        },
        
        {
            id: 1,
            username: `Juana Diez`,
            email: `judiez@gmail.com`,
            contrasena: `panqueque`,
            fecha_nacimiento: `2003-05-11`,
            dni: "46282929",
            image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS6oOF6CrDOU6SLZyGEeGiXrk4ec2XpwBUbjw&usqp=CAU",
        },
        {
            id: 2,
            username: `Lola Martinez`,
            email: `loli2003@gmail.com`,
            contrasena: `lola123456`,
            fecha_nacimiento: `2000-11-02`,
            dni: "455855272",
            image: "https://static.vecteezy.com/system/resources/previews/002/843/401/non_2x/cute-little-blond-girl-head-character-free-vector.jpg",
        },
        {
            id: 3,
            username: `Abril Perez`,
            email: `abril_perez@gmail.com`,
            contrasena: `abril123`,
            fecha_nacimiento: `2001-12-12`,
            dni: "415678817",
            image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSQyaYvYq_6lj6ykALDyEpx21Sv9WODUBGoTw&usqp=CAU",
        },
        {
            id: 4,
            username: `Azul Fernandez`,
            email: `fernandez_azul@gmail.com`,
            contrasena: `azulfer`,
            fecha_nacimiento: `2002-01-12`,
            dni: "41567617",
            image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSQyaYvYq_6lj6ykALDyEpx21Sv9WODUBGoTw&usqp=CAU",
        },

    ],


    comentarios: [
        {
            id:0,
            fecha:"18/02/2015",
            usuario: `amante_de_joyas`,
            texto: `Buenisima esta pieza, la recomiendo al 100%!`

        },
        {
            id:1,
            fecha: "18/02/2015",
            usuario: `juana_sanchez`,
            texto: `Piezas super autenticas y originales`
        },
        {
            id:2,
            fecha:"18/02/2015",
            usuario: `Joya_lovers`,
            texto: `Lugar super recomendado, piezas de excelente calidad y disenio!`
        },
        {
            id:3,
            fecha:"18/02/2015",
            usuario: `fan_de_collares123`,
            texto: `Me queria llevar todo! Muy buen trabajo y excelentes productos`
        },

    ]

}
module.exports = productos;